title: Ezteven blog
description: Me gusta ver el mundo desde otras perspectivas.
logo: /assets/icons/blog.ezteven.com.png
theme: jekyll-theme-cayman
google_analytics: UA-121844997-1
plugins:
    - jekyll-feed
    - jekyll-sitemap
algolia:
    application_id: PW3NQ2E296
    index_name: ezteven_blog
    search_only_api_key: 804f8616e8041fa89a9f59194d021ba9
    settings:
        attributesForFaceting:
            - lang
# Author details.
author:
    name: Esteban Quezada
    email: esteban.lds@outlook.com
    web: http://twitter.com/quezadaesteban